name: "Pimoroni Speaker pHAT"
description: "Use the Speaker pHAT to play sound from the Home Assistant host machine"
version: "1.0.40"
slug: "speakerphat"
url: https://github.com/ajwatt/home-assistant-addons/tree/main/speakerphat
init: false
arch:
  - armhf
audio: true
options:
  startup_sound: LGsong-chorus.wav
schema:
  startup_sound: str
