--- Makefile
+++ Makefile.latest
@@ -103,6 +103,7 @@
        $Q install -m 0755 -d                                           $(DESTDIR)$(PREFIX)/lib
        $Q install -m 0755 libwiringPi.so.$(VERSION)                    $(DESTDIR)$(PREFIX)/lib/libwiringPi.so.$(VERSION)
        $Q ln -sf $(DESTDIR)$(PREFIX)/lib/libwiringPi.so.$(VERSION)     $(DESTDIR)/lib/libwiringPi.so
+       $Q $(LDCONFIG)
 
 .PHONY: check-deb-destdir
 check-deb-destdir:
@@ -125,6 +126,7 @@
        $Q echo "[UnInstall]"
        $Q cd $(DESTDIR)$(PREFIX)/include/ && rm -f $(HEADERS)
        $Q cd $(DESTDIR)$(PREFIX)/lib/     && rm -f libwiringPi.*
+       $Q $(LDCONFIG)
 
 
 .PHONY:        depend
